name: idm
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.6
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - torchaudio=2.2.2
  - torchtriton=2.0.0=py310
  - torchvision=0.17.2
  - pip=23.3.1=py310h06a4308_0

  - pip:
      - accelerate==0.25.0
      - torchmetrics==1.2.1
      - tqdm==4.66.1
      - transformers==4.36.2
      - diffusers==0.25.0
      - einops==0.7.0
      - bitsandbytes==0.39.0
      - scipy==1.11.1
      - opencv-python
